name = "IsingZero"
uuid = "ba0fd749-0bd9-4cfd-b70b-7f5c4485429a"
authors = ["tomsmierz <smirzchalski.tomek@gmail.com>"]
version = "0.1.0"

[deps]
AlphaZero = "8ed9eb0b-7496-408d-8c8b-2119aeea02cd"
CommonRLInterface = "d842c3ba-07a1-494f-bbec-f5741b0a3e98"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
